client_config_backend: settings
client_config:
   #make sure these match the client_secrets.json
   client_id: '548853694688-uh246hksaivmh6tfdpvi324l0jouape0.apps.googleusercontent.com'
   client_secret: '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'

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
    - https://www.googleapis.com/auth/drive